PALETTES = {
    "ocean": ["blue", "cyan", "white"],
    "deep_ocean": ["blue", "cyan", "magenta"],
    "sea": ["cyan", "blue", "green"],
    "lagoon": ["cyan", "white", "green"],
    "arctic": ["white", "cyan", "blue"],
    "ice": ["white", "cyan", "blue"],
    "glacier": ["white", "blue", "cyan"],
    "sky": ["cyan", "white", "blue"],
    "cloud": ["white", "cyan"],
    "storm": ["white", "blue", "magenta"],

    "sunset": ["red", "yellow", "magenta"],
    "sunrise": ["yellow", "red", "white"],
    "dawn": ["yellow", "magenta", "white"],
    "dusk": ["magenta", "blue", "red"],
    "lava": ["red", "yellow"],
    "fire": ["red", "yellow", "white"],
    "ember": ["red", "magenta", "yellow"],
    "volcano": ["red", "white", "yellow"],
    "desert": ["yellow", "red"],
    "gold": ["yellow", "white"],

    "forest": ["green", "yellow"],
    "jungle": ["green", "cyan", "yellow"],
    "leaf": ["green", "white"],
    "grass": ["green", "yellow", "white"],
    "nature": ["green", "cyan"],
    "lime": ["green", "yellow"],
    "mint": ["green", "cyan", "white"],
    "emerald": ["green", "white"],
    "moss": ["green", "yellow", "magenta"],
    "spring": ["green", "yellow", "cyan"],

    "matrix": ["green", "white"],
    "terminal": ["green", "cyan"],
    "hacker": ["green", "white", "cyan"],
    "cyber": ["cyan", "magenta", "blue"],
    "cyberpunk": ["magenta", "cyan", "yellow"],
    "neon": ["cyan", "magenta", "blue"],
    "electric": ["cyan", "blue", "white"],
    "laser": ["red", "cyan"],
    "digital": ["cyan", "white", "green"],
    "quantum": ["blue", "magenta", "cyan"],

    "galaxy": ["magenta", "blue", "cyan"],
    "space": ["blue", "magenta", "white"],
    "nebula": ["magenta", "cyan", "blue"],
    "cosmos": ["blue", "white", "magenta"],
    "aurora": ["green", "cyan", "magenta"],
    "moonlight": ["white", "blue"],
    "starlight": ["white", "cyan", "magenta"],
    "midnight": ["blue", "magenta"],
    "eclipse": ["white", "magenta", "blue"],
    "comet": ["cyan", "white", "blue"],

    "royal": ["blue", "yellow", "white"],
    "luxury": ["yellow", "magenta", "white"],
    "diamond": ["white", "cyan"],
    "ruby": ["red", "magenta"],
    "sapphire": ["blue", "white"],
    "amethyst": ["magenta", "blue"],
    "pearl": ["white", "yellow"],
    "classic": ["white"],
    "mono": ["white"],
    "rainbow": ["red", "yellow", "green", "cyan", "blue", "magenta"],
}